-- GENERATED by scripts/build-setup-sql.mjs - do not edit; edit migrations/ or seed.sql instead.
-- Paste into Supabase Dashboard -> SQL Editor -> Run. Safe to re-run (idempotent).

-- ===== migrations/20240101000000_connection_test.sql =====
-- TULOY Health: connection test table (Task 2)
-- Proves every role (patient | bhw | admin) can read/write the shared backend.

CREATE TABLE IF NOT EXISTS public.connection_test (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message     TEXT NOT NULL,
  client_type TEXT NOT NULL CHECK (client_type IN ('patient', 'bhw', 'admin', 'system')),
  -- Set for rows created offline by a BHW, so retried syncs never duplicate them.
  local_id    TEXT UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS must be enabled; permissive policy is acceptable for the hackathon demo only.
ALTER TABLE public.connection_test ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for hackathon" ON public.connection_test;
CREATE POLICY "Allow all for hackathon"
  ON public.connection_test
  FOR ALL
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT ON public.connection_test TO anon, authenticated;

INSERT INTO public.connection_test (message, client_type)
SELECT * FROM (VALUES
  ('Initial system test', 'system'),
  ('Hackathon demo ready', 'system')
) AS seed(message, client_type)
WHERE NOT EXISTS (SELECT 1 FROM public.connection_test WHERE client_type = 'system');

-- ===== migrations/20240101000100_care_hierarchy.sql =====
-- TULOY Health: relational chain of command
--   admins  ->  bhws  ->  patients  ->  records
--
-- Admin creates/manages BHWs, BHWs register patients and log field records
-- (often offline, synced later), patients read the records their BHW created.
--
-- local_id columns let offline-created rows be upserted idempotently: if a sync
-- is retried after a partial failure, the same row is never inserted twice.

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name  TEXT NOT NULL,
  email      TEXT NOT NULL UNIQUE,
  office     TEXT NOT NULL DEFAULT 'Rural Health Unit',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- bhws (Barangay Health Workers), managed by an admin
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bhws (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id   UUID NOT NULL REFERENCES public.admins(id) ON DELETE RESTRICT,
  full_name  TEXT NOT NULL,
  email      TEXT UNIQUE,
  phone      TEXT,
  barangay   TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS bhws_admin_id_idx ON public.bhws(admin_id);

-- ---------------------------------------------------------------------------
-- patients, assigned to a BHW
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.patients (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bhw_id     UUID REFERENCES public.bhws(id) ON DELETE SET NULL,
  full_name  TEXT NOT NULL,
  sex        TEXT CHECK (sex IN ('F', 'M')),
  birth_date DATE,
  barangay   TEXT,
  address    TEXT,
  latitude   DOUBLE PRECISION,
  longitude  DOUBLE PRECISION,
  local_id   TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS patients_bhw_id_idx ON public.patients(bhw_id);

-- ---------------------------------------------------------------------------
-- records: visits, health updates and appointments a BHW logs for a patient
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.records (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id    UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  bhw_id        UUID REFERENCES public.bhws(id) ON DELETE SET NULL,
  record_type   TEXT NOT NULL CHECK (record_type IN ('visit', 'health_update', 'appointment')),
  title         TEXT NOT NULL,
  notes         TEXT,
  systolic      INTEGER CHECK (systolic BETWEEN 50 AND 260),
  diastolic     INTEGER CHECK (diastolic BETWEEN 30 AND 180),
  temperature_c NUMERIC(4, 1) CHECK (temperature_c BETWEEN 30 AND 45),
  weight_kg     NUMERIC(5, 1) CHECK (weight_kg BETWEEN 1 AND 400),
  scheduled_at  TIMESTAMPTZ,
  status        TEXT CHECK (status IN ('scheduled', 'completed', 'missed')),
  source        TEXT NOT NULL DEFAULT 'online' CHECK (source IN ('online', 'offline_sync')),
  local_id      TEXT UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS records_patient_id_idx ON public.records(patient_id);
CREATE INDEX IF NOT EXISTS records_bhw_id_idx ON public.records(bhw_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- RLS is ENABLED on every table. Policies are permissive for the hackathon demo
-- (no login flow; roles are hardcoded demo personas). Production must replace
-- these with auth.uid()-based policies, e.g. BHWs only see assigned patients.
-- No DELETE grant: the demo never deletes data from the client.
-- ---------------------------------------------------------------------------
ALTER TABLE public.admins   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bhws     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.records  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hackathon demo access" ON public.admins;
CREATE POLICY "Hackathon demo access" ON public.admins
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.bhws;
CREATE POLICY "Hackathon demo access" ON public.bhws
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.patients;
CREATE POLICY "Hackathon demo access" ON public.patients
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.records;
CREATE POLICY "Hackathon demo access" ON public.records
  FOR ALL USING (true) WITH CHECK (true);

GRANT SELECT                 ON public.admins   TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.bhws     TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.patients TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.records  TO anon, authenticated;

-- ===== migrations/20240101000200_shared_foundation.sql =====
-- TULOY Health: shared foundation (Spec 01)
--
-- Additive only: new tables, new columns, constraints, triggers and the
-- reset_demo_data() RPC. Nothing existing is renamed or dropped (the only
-- replaced object is records_record_type_check, widened to a superset).
--
-- Every statement is re-runnable, so this file can be applied to a database
-- that already has it (see supabase/apply_foundation.sql).
--   * ADD COLUMN IF NOT EXISTS without inline constraints
--   * named constraints via DROP CONSTRAINT IF EXISTS + ADD CONSTRAINT
--   * CREATE OR REPLACE FUNCTION, DROP TRIGGER/POLICY IF EXISTS + CREATE

-- ---------------------------------------------------------------------------
-- clinics (created first: patients.clinic_id references it)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.clinics (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                TEXT NOT NULL,
  address             TEXT,
  contact             TEXT,
  services            TEXT[] NOT NULL DEFAULT '{}',
  yakap_accreditation TEXT NOT NULL DEFAULT 'unknown',
  source              TEXT,
  last_verified_at    DATE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- New columns on existing tables (existing names kept: latitude/longitude,
-- address, bhws.status, created_at)
-- ---------------------------------------------------------------------------
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS admin_role   TEXT NOT NULL DEFAULT 'coordinator';
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS municipality TEXT;
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS is_demo      BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.bhws ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ;

ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS phone                TEXT;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS has_smartphone       BOOLEAN;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS yakap_stage          TEXT;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS clinic_id            UUID;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS sharing_consent      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS created_on_device_at TIMESTAMPTZ;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- All measurement columns are nullable: a missing reading is NULL, never 0.
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS measured_at          TIMESTAMPTZ;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS glucose_value        NUMERIC(6, 1);
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS glucose_unit         TEXT;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS glucose_test_type    TEXT;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS height_cm            NUMERIC(5, 1);
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS contact_outcome      TEXT;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS barrier              TEXT;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS next_action          TEXT;
-- origin = who produced the record. records.source keeps its existing meaning
-- (transport: 'online' | 'offline_sync') and is not changed.
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS origin               TEXT NOT NULL DEFAULT 'field';
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS transcription_status TEXT;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS review_status        TEXT;
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS created_on_device_at TIMESTAMPTZ;

-- ---------------------------------------------------------------------------
-- New tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.appointments (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id       UUID NOT NULL,
  clinic_id        UUID,
  purpose          TEXT NOT NULL,
  scheduled_at     TIMESTAMPTZ,
  encounter_status TEXT NOT NULL DEFAULT 'requested',
  owner_bhw_id     UUID,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.care_plans (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id         UUID NOT NULL,
  clinician_admin_id UUID,
  summary            TEXT NOT NULL,
  next_steps         TEXT,
  status             TEXT NOT NULL DEFAULT 'draft',
  released_at        TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The demo clinic inbox. id has NO default: the client generates it, and it is
-- the idempotency key for exactly-once delivery.
CREATE TABLE IF NOT EXISTS public.help_requests (
  id                   UUID PRIMARY KEY,
  patient_id           UUID NOT NULL,
  reason               TEXT NOT NULL,
  message              TEXT,
  created_on_device_at TIMESTAMPTZ NOT NULL,
  received_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  assigned_bhw_id      UUID,
  coordination_status  TEXT NOT NULL DEFAULT 'unassigned',
  acknowledged_at      TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- Seed flag on every table (reset_demo_data keeps is_seed rows only)
-- ---------------------------------------------------------------------------
ALTER TABLE public.connection_test ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.admins          ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.bhws            ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.patients        ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.records         ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.clinics         ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.appointments    ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.care_plans      ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.help_requests   ADD COLUMN IF NOT EXISTS is_seed BOOLEAN NOT NULL DEFAULT false;

-- The two system rows from the original connection_test migration survive resets.
UPDATE public.connection_test SET is_seed = true WHERE client_type = 'system' AND NOT is_seed;

-- ---------------------------------------------------------------------------
-- Constraints (named, re-runnable)
-- ---------------------------------------------------------------------------
-- Widened to the union of the old and new values; existing rows stay valid.
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_record_type_check;
ALTER TABLE public.records ADD CONSTRAINT records_record_type_check
  CHECK (record_type IN ('visit', 'health_update', 'appointment', 'vitals', 'lab_result', 'note'));

ALTER TABLE public.clinics DROP CONSTRAINT IF EXISTS clinics_yakap_accreditation_check;
ALTER TABLE public.clinics ADD CONSTRAINT clinics_yakap_accreditation_check
  CHECK (yakap_accreditation IN ('listed', 'unknown'));

ALTER TABLE public.admins DROP CONSTRAINT IF EXISTS admins_admin_role_check;
ALTER TABLE public.admins ADD CONSTRAINT admins_admin_role_check
  CHECK (admin_role IN ('coordinator', 'clinician'));

ALTER TABLE public.patients DROP CONSTRAINT IF EXISTS patients_yakap_stage_check;
ALTER TABLE public.patients ADD CONSTRAINT patients_yakap_stage_check
  CHECK (yakap_stage IN (
    'need_help_getting_started', 'clinic_selected_pending', 'first_checkup_planned',
    'checkup_and_assessment', 'tests_requested', 'results_review_pending',
    'plan_available', 'continued_monitoring'
  ));

ALTER TABLE public.patients DROP CONSTRAINT IF EXISTS patients_clinic_id_fkey;
ALTER TABLE public.patients ADD CONSTRAINT patients_clinic_id_fkey
  FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) ON DELETE SET NULL;

ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_glucose_value_check;
ALTER TABLE public.records ADD CONSTRAINT records_glucose_value_check CHECK (glucose_value > 0);
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_glucose_unit_check;
ALTER TABLE public.records ADD CONSTRAINT records_glucose_unit_check CHECK (glucose_unit IN ('mg/dL', 'mmol/L'));
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_glucose_test_type_check;
ALTER TABLE public.records ADD CONSTRAINT records_glucose_test_type_check
  CHECK (glucose_test_type IN ('fasting', 'random', 'post_meal'));
-- A glucose value is meaningless without its unit and test type.
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_glucose_complete_check;
ALTER TABLE public.records ADD CONSTRAINT records_glucose_complete_check
  CHECK (glucose_value IS NULL OR (glucose_unit IS NOT NULL AND glucose_test_type IS NOT NULL));
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_height_cm_check;
ALTER TABLE public.records ADD CONSTRAINT records_height_cm_check CHECK (height_cm BETWEEN 30 AND 250);
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_origin_check;
ALTER TABLE public.records ADD CONSTRAINT records_origin_check CHECK (origin IN ('field', 'patient', 'clinic'));
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_transcription_status_check;
ALTER TABLE public.records ADD CONSTRAINT records_transcription_status_check
  CHECK (transcription_status IN ('pending', 'confirmed'));
ALTER TABLE public.records DROP CONSTRAINT IF EXISTS records_review_status_check;
ALTER TABLE public.records ADD CONSTRAINT records_review_status_check
  CHECK (review_status IN ('awaiting_clinical_review', 'plan_released'));

ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_patient_id_fkey;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_patient_id_fkey
  FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_clinic_id_fkey;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_clinic_id_fkey
  FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) ON DELETE SET NULL;
ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_owner_bhw_id_fkey;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_owner_bhw_id_fkey
  FOREIGN KEY (owner_bhw_id) REFERENCES public.bhws(id) ON DELETE SET NULL;
ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_encounter_status_check;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_encounter_status_check
  CHECK (encounter_status IN (
    'requested', 'confirmed', 'patient_reported_attended', 'clinic_confirmed_attended', 'missed', 'rescheduled'
  ));

ALTER TABLE public.care_plans DROP CONSTRAINT IF EXISTS care_plans_patient_id_fkey;
ALTER TABLE public.care_plans ADD CONSTRAINT care_plans_patient_id_fkey
  FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.care_plans DROP CONSTRAINT IF EXISTS care_plans_clinician_admin_id_fkey;
ALTER TABLE public.care_plans ADD CONSTRAINT care_plans_clinician_admin_id_fkey
  FOREIGN KEY (clinician_admin_id) REFERENCES public.admins(id) ON DELETE SET NULL;
ALTER TABLE public.care_plans DROP CONSTRAINT IF EXISTS care_plans_status_check;
ALTER TABLE public.care_plans ADD CONSTRAINT care_plans_status_check CHECK (status IN ('draft', 'released'));
ALTER TABLE public.care_plans DROP CONSTRAINT IF EXISTS care_plans_released_at_check;
ALTER TABLE public.care_plans ADD CONSTRAINT care_plans_released_at_check
  CHECK (status <> 'released' OR released_at IS NOT NULL);

ALTER TABLE public.help_requests DROP CONSTRAINT IF EXISTS help_requests_patient_id_fkey;
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_patient_id_fkey
  FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.help_requests DROP CONSTRAINT IF EXISTS help_requests_assigned_bhw_id_fkey;
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_assigned_bhw_id_fkey
  FOREIGN KEY (assigned_bhw_id) REFERENCES public.bhws(id) ON DELETE SET NULL;
ALTER TABLE public.help_requests DROP CONSTRAINT IF EXISTS help_requests_reason_check;
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_reason_check
  CHECK (reason IN ('transport', 'another_date', 'lab_access', 'document_help', 'medicine_access', 'other'));
ALTER TABLE public.help_requests DROP CONSTRAINT IF EXISTS help_requests_message_check;
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_message_check CHECK (char_length(message) <= 500);
ALTER TABLE public.help_requests DROP CONSTRAINT IF EXISTS help_requests_coordination_status_check;
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_coordination_status_check
  CHECK (coordination_status IN ('unassigned', 'assigned', 'acknowledged', 'blocked', 'completed'));

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS patients_clinic_id_idx                ON public.patients(clinic_id);
CREATE INDEX IF NOT EXISTS appointments_patient_id_idx           ON public.appointments(patient_id);
CREATE INDEX IF NOT EXISTS care_plans_patient_id_idx             ON public.care_plans(patient_id);
CREATE INDEX IF NOT EXISTS help_requests_patient_id_idx          ON public.help_requests(patient_id);
CREATE INDEX IF NOT EXISTS help_requests_assigned_bhw_id_idx     ON public.help_requests(assigned_bhw_id);
CREATE INDEX IF NOT EXISTS help_requests_coordination_status_idx ON public.help_requests(coordination_status);

-- ---------------------------------------------------------------------------
-- Row Level Security: ENABLED, permissive for the hackathon demo (same style
-- as 20240101000100_care_hierarchy.sql). No DELETE grant to clients.
-- ---------------------------------------------------------------------------
ALTER TABLE public.clinics       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.care_plans    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.help_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hackathon demo access" ON public.clinics;
CREATE POLICY "Hackathon demo access" ON public.clinics
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.appointments;
CREATE POLICY "Hackathon demo access" ON public.appointments
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.care_plans;
CREATE POLICY "Hackathon demo access" ON public.care_plans
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.help_requests;
CREATE POLICY "Hackathon demo access" ON public.help_requests
  FOR ALL USING (true) WITH CHECK (true);

GRANT SELECT                 ON public.clinics       TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.appointments  TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.care_plans    TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.help_requests TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- Seed guard: clients (anon/authenticated) can never create or edit is_seed,
-- so Reset demo data stays deterministic. The SQL Editor and the
-- security-definer reset run as the table owner and are unaffected.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.guard_is_seed()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF current_user IN ('anon', 'authenticated') THEN
    IF TG_OP = 'INSERT' THEN
      NEW.is_seed := false;
    ELSE
      NEW.is_seed := OLD.is_seed;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'connection_test', 'admins', 'bhws', 'patients', 'records',
    'clinics', 'appointments', 'care_plans', 'help_requests'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS tg_10_guard_is_seed ON public.%I', t);
    EXECUTE format(
      'CREATE TRIGGER tg_10_guard_is_seed BEFORE INSERT OR UPDATE ON public.%I '
      'FOR EACH ROW EXECUTE FUNCTION public.guard_is_seed()', t);
  END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- Help-request auto-assignment: the patient's BHW owns the request.
-- No BHW -> stays 'unassigned' and shows in RHU Needs Attention.
-- Runs after tg_10_guard_is_seed (triggers fire in name order).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.help_request_before_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  -- Received time is always the server's, never the client's.
  IF NOT NEW.is_seed THEN
    NEW.received_at := now();
  END IF;

  IF NEW.assigned_bhw_id IS NULL THEN
    SELECT p.bhw_id INTO NEW.assigned_bhw_id FROM public.patients p WHERE p.id = NEW.patient_id;
    IF NEW.assigned_bhw_id IS NOT NULL AND NEW.coordination_status = 'unassigned' THEN
      NEW.coordination_status := 'assigned';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_20_help_request_assign ON public.help_requests;
CREATE TRIGGER tg_20_help_request_assign
  BEFORE INSERT ON public.help_requests
  FOR EACH ROW EXECUTE FUNCTION public.help_request_before_insert();

-- ---------------------------------------------------------------------------
-- reset_demo_data(): deletes every non-seed row and restores the seed rows.
-- SECURITY DEFINER because clients have no DELETE grant.
-- WARNING: anyone holding the anon key can call this. Acceptable for the
-- hackathon demo database only; production must remove the grant below.
-- apply_demo_seed() is defined in supabase/seed.sql.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.reset_demo_data(
  center_lat DOUBLE PRECISION DEFAULT 14.5995,
  center_lng DOUBLE PRECISION DEFAULT 120.9842
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted jsonb := '{}'::jsonb;
  n INTEGER;
BEGIN
  IF center_lat IS NULL OR center_lng IS NULL
     OR center_lat NOT BETWEEN -89 AND 89 OR center_lng NOT BETWEEN -179 AND 179 THEN
    RAISE EXCEPTION 'Invalid demo map centre (%, %)', center_lat, center_lng;
  END IF;

  IF to_regprocedure('public.apply_demo_seed(double precision,double precision)') IS NULL THEN
    RAISE EXCEPTION 'Seed not loaded. Run supabase/seed.sql.';
  END IF;

  -- 1. Non-seed rows, children before parents.
  DELETE FROM public.help_requests   WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('help_requests', n);
  DELETE FROM public.care_plans      WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('care_plans', n);
  DELETE FROM public.appointments    WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('appointments', n);
  DELETE FROM public.records         WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('records', n);
  DELETE FROM public.connection_test WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('connection_test', n);
  DELETE FROM public.patients        WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('patients', n);
  DELETE FROM public.bhws            WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('bhws', n);

  -- 2. Restore every seed row to its original values (also re-points any seed
  --    row that referenced a non-seed admin or clinic).
  PERFORM public.apply_demo_seed(center_lat, center_lng);

  -- 3. Parents that seed rows no longer reference.
  DELETE FROM public.admins  WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('admins', n);
  DELETE FROM public.clinics WHERE NOT is_seed; GET DIAGNOSTICS n = ROW_COUNT; deleted := deleted || jsonb_build_object('clinics', n);

  RETURN jsonb_build_object('deleted', deleted, 'reset_at', now());
END;
$$;

REVOKE ALL ON FUNCTION public.reset_demo_data(DOUBLE PRECISION, DOUBLE PRECISION) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_demo_data(DOUBLE PRECISION, DOUBLE PRECISION) TO anon, authenticated;

-- Make the new tables and RPC visible to the Data API immediately.
NOTIFY pgrst, 'reload schema';

-- ===== seed.sql =====
-- TULOY Health demo seed (Spec 01). All data is synthetic DEMO DATA.
--
-- The seed lives in one function, apply_demo_seed(), so that the same values are
-- used by a fresh setup and by reset_demo_data() (Reset demo data).
--   * Fixed UUIDs match apps/mobile/src/shared/config/demo.ts.
--   * Every row is upserted with ON CONFLICT (id) DO UPDATE and is_seed = true,
--     so re-running restores edited seed rows and renames old personas in place.
--   * Times are anchored to t0 = the moment of the seed/reset, so every run shows
--     the same relative timeline ("follow-up in 4 days").
--   * Patient coordinates are small fixed offsets (|d| <= 0.01 deg) around the
--     demo map centre and labelled "approximate DEMO location". No real addresses.
--   * Unmeasured values are NULL, never 0.

CREATE OR REPLACE FUNCTION public.apply_demo_seed(
  center_lat DOUBLE PRECISION DEFAULT 14.5995,
  center_lng DOUBLE PRECISION DEFAULT 120.9842
)
RETURNS void
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  t0 TIMESTAMPTZ := date_trunc('minute', now());
  d0 DATE := current_date;
  -- Persona IDs
  admin_carmen UUID := 'a0000000-0000-4000-8000-000000000001';
  admin_ramon  UUID := 'a0000000-0000-4000-8000-000000000002';
  bhw_liza     UUID := 'b0000000-0000-4000-8000-000000000001';
  bhw_joel     UUID := 'b0000000-0000-4000-8000-000000000002';
  bhw_ana      UUID := 'b0000000-0000-4000-8000-000000000003';
  clinic_rhu   UUID := 'e0000000-0000-4000-8000-000000000001';
  clinic_bhs   UUID := 'e0000000-0000-4000-8000-000000000002';
  clinic_fam   UUID := 'e0000000-0000-4000-8000-000000000003';
  p_juana      UUID := 'c0000000-0000-4000-8000-000000000001';
  p_pedro      UUID := 'c0000000-0000-4000-8000-000000000002';
  p_rosa       UUID := 'c0000000-0000-4000-8000-000000000003';
  p_lito       UUID := 'c0000000-0000-4000-8000-000000000004';
  p_marites    UUID := 'c0000000-0000-4000-8000-000000000005';
  p_ernesto    UUID := 'c0000000-0000-4000-8000-000000000006';
  p_lorna      UUID := 'c0000000-0000-4000-8000-000000000007';
  p_nestor     UUID := 'c0000000-0000-4000-8000-000000000008';
BEGIN
  IF center_lat IS NULL OR center_lng IS NULL
     OR center_lat NOT BETWEEN -89 AND 89 OR center_lng NOT BETWEEN -179 AND 179 THEN
    RAISE EXCEPTION 'Invalid demo map centre (%, %)', center_lat, center_lng;
  END IF;

  -- -------------------------------------------------------------------------
  -- Admins: coordinator + clinician (email is NOT NULL UNIQUE)
  -- -------------------------------------------------------------------------
  INSERT INTO public.admins AS t (id, full_name, email, office, admin_role, municipality, is_demo, created_at, is_seed) VALUES
    (admin_carmen, 'Carmen Reyes (DEMO)',     'demo.admin@tuloy.test',     'Demo Rural Health Unit (DEMO)', 'coordinator', 'Demo Municipality (DEMO)', true, t0 - INTERVAL '120 days', true),
    (admin_ramon,  'Dr. Ramon Santos (DEMO)', 'demo.clinician@tuloy.test', 'Demo Rural Health Unit (DEMO)', 'clinician',   'Demo Municipality (DEMO)', true, t0 - INTERVAL '120 days', true)
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name, email = EXCLUDED.email, office = EXCLUDED.office,
    admin_role = EXCLUDED.admin_role, municipality = EXCLUDED.municipality, is_demo = EXCLUDED.is_demo,
    created_at = EXCLUDED.created_at, is_seed = true;

  -- -------------------------------------------------------------------------
  -- BHWs: Liza and Joel active, Ana inactive for 5 days
  -- -------------------------------------------------------------------------
  INSERT INTO public.bhws AS t (id, admin_id, full_name, email, phone, barangay, status, last_active_at, created_at, is_seed) VALUES
    (bhw_liza, admin_carmen, 'Liza Mendoza (DEMO)',   'demo.bhw1@tuloy.test', '0900-000-0001', 'Brgy. Demo San Isidro',     'active',   t0 - INTERVAL '2 hours', t0 - INTERVAL '110 days', true),
    (bhw_joel, admin_carmen, 'Joel Bautista (DEMO)',  'demo.bhw2@tuloy.test', '0900-000-0002', 'Brgy. Demo Malinis',        'active',   t0 - INTERVAL '1 day',   t0 - INTERVAL '110 days', true),
    (bhw_ana,  admin_carmen, 'Ana Villanueva (DEMO)', 'demo.bhw3@tuloy.test', '0900-000-0003', 'Brgy. Demo Bagong Pag-asa', 'inactive', t0 - INTERVAL '5 days',  t0 - INTERVAL '110 days', true)
  ON CONFLICT (id) DO UPDATE SET
    admin_id = EXCLUDED.admin_id, full_name = EXCLUDED.full_name, email = EXCLUDED.email, phone = EXCLUDED.phone,
    barangay = EXCLUDED.barangay, status = EXCLUDED.status, last_active_at = EXCLUDED.last_active_at,
    created_at = EXCLUDED.created_at, is_seed = true;

  -- -------------------------------------------------------------------------
  -- Clinics: synthetic. e...03 has unknown accreditation and an old verification.
  -- -------------------------------------------------------------------------
  INSERT INTO public.clinics AS t (id, name, address, contact, services, yakap_accreditation, source, last_verified_at, created_at, is_seed) VALUES
    (clinic_rhu, 'Demo Rural Health Unit Clinic (DEMO)', 'Poblacion, Demo Municipality (DEMO)', '0900-000-2001',
       ARRAY['Consultation', 'Blood pressure check', 'Fasting blood sugar', 'Prenatal care'], 'listed',
       'Synthetic demo entry (DEMO)', d0 - 20, t0 - INTERVAL '120 days', true),
    (clinic_bhs, 'Demo Barangay Health Station (DEMO)', 'Brgy. Demo San Isidro (DEMO)', '0900-000-2002',
       ARRAY['Blood pressure check', 'Immunization'], 'listed',
       'Synthetic demo entry (DEMO)', d0 - 45, t0 - INTERVAL '120 days', true),
    (clinic_fam, 'Demo Family Clinic (DEMO)', 'Brgy. Demo Malinis (DEMO)', '0900-000-2003',
       ARRAY['Consultation'], 'unknown',
       'Synthetic demo entry (DEMO); accreditation not confirmed', DATE '2024-03-01', t0 - INTERVAL '120 days', true)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, address = EXCLUDED.address, contact = EXCLUDED.contact, services = EXCLUDED.services,
    yakap_accreditation = EXCLUDED.yakap_accreditation, source = EXCLUDED.source,
    last_verified_at = EXCLUDED.last_verified_at, created_at = EXCLUDED.created_at, is_seed = true;

  -- -------------------------------------------------------------------------
  -- Patients: Juana + 7 cases (product.md section 7)
  -- -------------------------------------------------------------------------
  INSERT INTO public.patients AS t (
    id, bhw_id, full_name, sex, birth_date, barangay, address, latitude, longitude, local_id,
    phone, has_smartphone, yakap_stage, clinic_id, sharing_consent, created_on_device_at, created_at, updated_at, is_seed
  ) VALUES
    -- Primary patient: confirmed follow-up, released care plan
    (p_juana, bhw_liza, 'Juana Dela Cruz (DEMO)', 'F', DATE '1968-04-12', 'Brgy. Demo San Isidro',
       'Purok 1 (DEMO) · approximate DEMO location', center_lat + 0.0047, center_lng - 0.0020, NULL,
       '0900-000-1001', true, 'plan_available', clinic_rhu, true, NULL, t0 - INTERVAL '100 days', t0 - INTERVAL '10 days', true),
    -- Unknown attendance (past confirmed appointment, no attendance recorded)
    (p_pedro, bhw_liza, 'Pedro Garcia (DEMO)', 'M', DATE '1955-09-30', 'Brgy. Demo San Isidro',
       'Purok 2 (DEMO) · approximate DEMO location', center_lat - 0.0027, center_lng + 0.0048, NULL,
       '0900-000-1002', true, 'first_checkup_planned', clinic_bhs, true, NULL, t0 - INTERVAL '95 days', t0 - INTERVAL '3 days', true),
    -- Confirmed missed follow-up
    (p_rosa, bhw_liza, 'Rosa Aquino (DEMO)', 'F', DATE '1990-01-05', 'Brgy. Demo San Isidro',
       'Purok 3 (DEMO) · approximate DEMO location', center_lat - 0.0064, center_lng - 0.0041, NULL,
       '0900-000-1003', true, 'continued_monitoring', clinic_rhu, true, NULL, t0 - INTERVAL '90 days', t0 - INTERVAL '10 days', true),
    -- Result awaiting clinical review
    (p_lito, bhw_joel, 'Lito Ramos (DEMO)', 'M', DATE '1972-06-18', 'Brgy. Demo Malinis',
       'Purok 1 (DEMO) · approximate DEMO location', center_lat + 0.0085, center_lng + 0.0093, NULL,
       '0900-000-1004', true, 'results_review_pending', clinic_rhu, true, NULL, t0 - INTERVAL '85 days', t0 - INTERVAL '7 days', true),
    -- Unresolved transport barrier
    (p_marites, bhw_joel, 'Marites Flores (DEMO)', 'F', DATE '1983-11-23', 'Brgy. Demo Malinis',
       'Purok 4 (DEMO) · approximate DEMO location', center_lat + 0.0016, center_lng + 0.0099, NULL,
       '0900-000-1005', true, 'clinic_selected_pending', clinic_rhu, true, NULL, t0 - INTERVAL '60 days', t0 - INTERVAL '2 days', true),
    -- Unassigned (no BHW): shows in RHU Needs Attention
    (p_ernesto, NULL, 'Ernesto Villar (DEMO)', 'M', DATE '1961-02-14', 'Brgy. Demo Bagong Pag-asa',
       'Purok 2 (DEMO) · approximate DEMO location', center_lat - 0.0091, center_lng + 0.0022, NULL,
       '0900-000-1006', true, 'need_help_getting_started', NULL, false, NULL, t0 - INTERVAL '4 days', t0 - INTERVAL '1 day', true),
    -- No smartphone: assisted by the BHW
    (p_lorna, bhw_liza, 'Lorna Pascual (DEMO)', 'F', DATE '1949-07-08', 'Brgy. Demo San Isidro',
       'Purok 5 (DEMO) · approximate DEMO location', center_lat + 0.0032, center_lng - 0.0076, NULL,
       NULL, false, 'checkup_and_assessment', clinic_bhs, true, NULL, t0 - INTERVAL '70 days', t0 - INTERVAL '9 days', true),
    -- Newly onboarded, no measurements ("No readings yet", never 0)
    (p_nestor, bhw_joel, 'Nestor Manalo (DEMO)', 'M', DATE '1998-12-01', 'Brgy. Demo Malinis',
       'Purok 2 (DEMO) · approximate DEMO location', center_lat - 0.0045, center_lng + 0.0067, NULL,
       '0900-000-1008', true, 'need_help_getting_started', NULL, true, t0 - INTERVAL '1 day', t0 - INTERVAL '1 day', t0 - INTERVAL '1 day', true)
  ON CONFLICT (id) DO UPDATE SET
    bhw_id = EXCLUDED.bhw_id, full_name = EXCLUDED.full_name, sex = EXCLUDED.sex, birth_date = EXCLUDED.birth_date,
    barangay = EXCLUDED.barangay, address = EXCLUDED.address, latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
    local_id = EXCLUDED.local_id, phone = EXCLUDED.phone, has_smartphone = EXCLUDED.has_smartphone,
    yakap_stage = EXCLUDED.yakap_stage, clinic_id = EXCLUDED.clinic_id, sharing_consent = EXCLUDED.sharing_consent,
    created_on_device_at = EXCLUDED.created_on_device_at, created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at, is_seed = true;

  -- -------------------------------------------------------------------------
  -- Records (field records). Juana: 3 BP readings in 3 different months
  -- (-84 / -52 / -12 days are >= 32 days apart pairwise). Nestor: none.
  -- -------------------------------------------------------------------------
  INSERT INTO public.records AS t (
    id, patient_id, bhw_id, record_type, title, notes,
    systolic, diastolic, temperature_c, weight_kg, height_cm,
    glucose_value, glucose_unit, glucose_test_type,
    scheduled_at, status, source, local_id, origin,
    contact_outcome, barrier, next_action, transcription_status, review_status,
    measured_at, created_on_device_at, created_at, is_seed
  ) VALUES
    ('d0000000-0000-4000-8000-000000000001', p_juana, bhw_liza, 'visit', 'Home visit: BP check',
       'Demo note: advised low-salt diet.', 148, 94, 36.7, 61.5, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', 'reached', NULL, 'Recheck BP in 1 month', NULL, NULL,
       t0 - INTERVAL '84 days', t0 - INTERVAL '84 days', t0 - INTERVAL '84 days', true),
    ('d0000000-0000-4000-8000-000000000008', p_juana, bhw_liza, 'vitals', 'BP recheck',
       'Demo note: home reading.', 138, 88, NULL, NULL, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', NULL, NULL, NULL, NULL, NULL,
       t0 - INTERVAL '52 days', t0 - INTERVAL '52 days', t0 - INTERVAL '52 days', true),
    ('d0000000-0000-4000-8000-000000000009', p_juana, bhw_liza, 'vitals', 'BP, weight and height',
       'Demo note: measured at the barangay health station.', 132, 84, NULL, 61.0, 152.0, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', NULL, NULL, NULL, NULL, NULL,
       t0 - INTERVAL '12 days', t0 - INTERVAL '12 days', t0 - INTERVAL '12 days', true),
    ('d0000000-0000-4000-8000-000000000002', p_juana, bhw_liza, 'health_update', 'Maintenance meds refilled',
       'Demo note: 30-day supply given.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', NULL, NULL, NULL, NULL, NULL,
       NULL, t0 - INTERVAL '12 days', t0 - INTERVAL '12 days', true),
    -- Legacy appointment record kept so existing Patient screens still show the
    -- follow-up; the same visit is appointments f...01.
    ('d0000000-0000-4000-8000-000000000003', p_juana, bhw_liza, 'appointment', 'Follow-up BP check at RHU',
       'Demo note: bring medication list.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
       t0 + INTERVAL '4 days', 'scheduled', 'online', NULL, 'field', NULL, NULL, NULL, NULL, NULL,
       NULL, t0 - INTERVAL '10 days', t0 - INTERVAL '10 days', true),
    ('d0000000-0000-4000-8000-000000000004', p_pedro, bhw_liza, 'visit', 'Home visit: BP check',
       'Demo note: invited to a preventive checkup.', 128, 82, 36.5, 70.2, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', 'reached', NULL, 'Confirm checkup attendance', NULL, NULL,
       t0 - INTERVAL '20 days', t0 - INTERVAL '20 days', t0 - INTERVAL '20 days', true),
    ('d0000000-0000-4000-8000-000000000005', p_rosa, bhw_liza, 'visit', 'Home visit: BP check',
       'Demo note: follow-up consultation scheduled.', 120, 78, NULL, NULL, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', 'reached', NULL, NULL, NULL, NULL,
       t0 - INTERVAL '40 days', t0 - INTERVAL '40 days', t0 - INTERVAL '40 days', true),
    ('d0000000-0000-4000-8000-000000000006', p_lito, bhw_joel, 'visit', 'Home visit: BP check',
       'Demo note: referred for a fasting blood sugar test.', 118, 76, 37.1, 58.0, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', 'reached', NULL, 'Fasting blood sugar test at RHU', NULL, NULL,
       t0 - INTERVAL '14 days', t0 - INTERVAL '14 days', t0 - INTERVAL '14 days', true),
    ('d0000000-0000-4000-8000-000000000010', p_lito, bhw_joel, 'lab_result', 'Fasting blood sugar result',
       'Demo note: transcribed from the clinic slip.', NULL, NULL, NULL, NULL, NULL, 126.0, 'mg/dL', 'fasting',
       NULL, NULL, 'online', NULL, 'clinic', NULL, NULL, NULL, 'confirmed', 'awaiting_clinical_review',
       t0 - INTERVAL '7 days', t0 - INTERVAL '6 days', t0 - INTERVAL '6 days', true),
    ('d0000000-0000-4000-8000-000000000007', p_marites, bhw_joel, 'health_update', 'Clinic selected',
       'Demo note: chose the RHU clinic; confirmation pending.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', NULL, NULL, NULL, NULL, NULL,
       NULL, t0 - INTERVAL '5 days', t0 - INTERVAL '5 days', true),
    ('d0000000-0000-4000-8000-000000000011', p_marites, bhw_joel, 'visit', 'Home visit: transport barrier',
       'Demo note: no ride to the RHU for the first checkup.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', 'reached', 'transport', 'Arrange transport to RHU', NULL, NULL,
       NULL, t0 - INTERVAL '2 days', t0 - INTERVAL '2 days', true),
    ('d0000000-0000-4000-8000-000000000012', p_lorna, bhw_liza, 'visit', 'Assisted home visit',
       'Assisted visit (no smartphone).', 124, 80, NULL, NULL, NULL, NULL, NULL, NULL,
       NULL, NULL, 'online', NULL, 'field', 'reached', NULL, 'Next home visit in 2 weeks', NULL, NULL,
       t0 - INTERVAL '9 days', t0 - INTERVAL '9 days', t0 - INTERVAL '9 days', true)
  ON CONFLICT (id) DO UPDATE SET
    patient_id = EXCLUDED.patient_id, bhw_id = EXCLUDED.bhw_id, record_type = EXCLUDED.record_type,
    title = EXCLUDED.title, notes = EXCLUDED.notes, systolic = EXCLUDED.systolic, diastolic = EXCLUDED.diastolic,
    temperature_c = EXCLUDED.temperature_c, weight_kg = EXCLUDED.weight_kg, height_cm = EXCLUDED.height_cm,
    glucose_value = EXCLUDED.glucose_value, glucose_unit = EXCLUDED.glucose_unit,
    glucose_test_type = EXCLUDED.glucose_test_type, scheduled_at = EXCLUDED.scheduled_at, status = EXCLUDED.status,
    source = EXCLUDED.source, local_id = EXCLUDED.local_id, origin = EXCLUDED.origin,
    contact_outcome = EXCLUDED.contact_outcome, barrier = EXCLUDED.barrier, next_action = EXCLUDED.next_action,
    transcription_status = EXCLUDED.transcription_status, review_status = EXCLUDED.review_status,
    measured_at = EXCLUDED.measured_at, created_on_device_at = EXCLUDED.created_on_device_at,
    created_at = EXCLUDED.created_at, is_seed = true;

  -- -------------------------------------------------------------------------
  -- Appointments (encounter dictionary values)
  -- -------------------------------------------------------------------------
  INSERT INTO public.appointments AS t (id, patient_id, clinic_id, purpose, scheduled_at, encounter_status, owner_bhw_id, created_at, updated_at, is_seed) VALUES
    ('f0000000-0000-4000-8000-000000000001', p_juana,   clinic_rhu, 'Follow-up BP check (DEMO)',       t0 + INTERVAL '4 days',  'confirmed',                 bhw_liza, t0 - INTERVAL '10 days', t0 - INTERVAL '10 days', true),
    ('f0000000-0000-4000-8000-000000000002', p_pedro,   clinic_bhs, 'Preventive checkup (DEMO)',       t0 - INTERVAL '3 days',  'confirmed',                 bhw_liza, t0 - INTERVAL '20 days', t0 - INTERVAL '20 days', true),
    ('f0000000-0000-4000-8000-000000000003', p_rosa,    clinic_rhu, 'Follow-up consultation (DEMO)',   t0 - INTERVAL '10 days', 'missed',                    bhw_liza, t0 - INTERVAL '40 days', t0 - INTERVAL '9 days',  true),
    ('f0000000-0000-4000-8000-000000000004', p_lito,    clinic_rhu, 'Fasting blood sugar test (DEMO)', t0 - INTERVAL '7 days',  'clinic_confirmed_attended', bhw_joel, t0 - INTERVAL '14 days', t0 - INTERVAL '7 days',  true),
    ('f0000000-0000-4000-8000-000000000005', p_marites, clinic_rhu, 'First YAKAP checkup (DEMO)',      t0 + INTERVAL '6 days',  'requested',                 bhw_joel, t0 - INTERVAL '5 days',  t0 - INTERVAL '5 days',  true)
  ON CONFLICT (id) DO UPDATE SET
    patient_id = EXCLUDED.patient_id, clinic_id = EXCLUDED.clinic_id, purpose = EXCLUDED.purpose,
    scheduled_at = EXCLUDED.scheduled_at, encounter_status = EXCLUDED.encounter_status,
    owner_bhw_id = EXCLUDED.owner_bhw_id, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at,
    is_seed = true;

  -- -------------------------------------------------------------------------
  -- Care plan: released by the clinician for Juana (no diagnosis wording)
  -- -------------------------------------------------------------------------
  INSERT INTO public.care_plans AS t (id, patient_id, clinician_admin_id, summary, next_steps, status, released_at, created_at, updated_at, is_seed) VALUES
    ('90000000-0000-4000-8000-000000000001', p_juana, admin_ramon,
       'Your recent blood pressure readings were reviewed by your clinician (DEMO).',
       'Keep taking your maintenance medicine as prescribed. Attend your follow-up BP check at the RHU. Ask your BHW if you need help getting there.',
       'released', t0 - INTERVAL '10 days', t0 - INTERVAL '11 days', t0 - INTERVAL '10 days', true)
  ON CONFLICT (id) DO UPDATE SET
    patient_id = EXCLUDED.patient_id, clinician_admin_id = EXCLUDED.clinician_admin_id, summary = EXCLUDED.summary,
    next_steps = EXCLUDED.next_steps, status = EXCLUDED.status, released_at = EXCLUDED.released_at,
    created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, is_seed = true;

  -- -------------------------------------------------------------------------
  -- Help requests. None for Juana: her live demo request is the only new item.
  -- -------------------------------------------------------------------------
  INSERT INTO public.help_requests AS t (id, patient_id, reason, message, created_on_device_at, received_at, assigned_bhw_id, coordination_status, acknowledged_at, is_seed) VALUES
    ('80000000-0000-4000-8000-000000000001', p_marites, 'transport', 'I have no ride to the RHU for my checkup. (DEMO)',
       t0 - INTERVAL '2 days 1 hour', t0 - INTERVAL '2 days', bhw_joel, 'blocked', t0 - INTERVAL '2 days' + INTERVAL '3 hours', true),
    ('80000000-0000-4000-8000-000000000002', p_ernesto, 'document_help', 'I need help with my PhilHealth documents. (DEMO)',
       t0 - INTERVAL '1 day 2 hours', t0 - INTERVAL '1 day', NULL, 'unassigned', NULL, true)
  ON CONFLICT (id) DO UPDATE SET
    patient_id = EXCLUDED.patient_id, reason = EXCLUDED.reason, message = EXCLUDED.message,
    created_on_device_at = EXCLUDED.created_on_device_at, received_at = EXCLUDED.received_at,
    assigned_bhw_id = EXCLUDED.assigned_bhw_id, coordination_status = EXCLUDED.coordination_status,
    acknowledged_at = EXCLUDED.acknowledged_at, is_seed = true;
END;
$$;

-- Only reset_demo_data() (security definer) and the SQL Editor may run the seed.
-- Supabase grants EXECUTE on new public functions to anon/authenticated by default.
REVOKE ALL ON FUNCTION public.apply_demo_seed(DOUBLE PRECISION, DOUBLE PRECISION) FROM PUBLIC;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON FUNCTION public.apply_demo_seed(DOUBLE PRECISION, DOUBLE PRECISION) FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON FUNCTION public.apply_demo_seed(DOUBLE PRECISION, DOUBLE PRECISION) FROM authenticated;
  END IF;
END;
$$;

SELECT public.apply_demo_seed();

-- Make the new tables visible to the Data API immediately.
NOTIFY pgrst, 'reload schema';
