-- GENERATED by scripts/build-setup-sql.mjs - do not edit; edit migrations/ or seed.sql instead.
-- Paste into Supabase Dashboard -> SQL Editor -> Run. Safe to re-run (idempotent).

-- ===== migrations/20240101000000_connection_test.sql =====
-- TULOY Health: connection test table (Task 2)
-- Proves every role (patient | bhw | admin) can read/write the shared backend.

CREATE TABLE IF NOT EXISTS public.connection_test (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message     TEXT NOT NULL,
  client_type TEXT NOT NULL CHECK (client_type IN ('patient', 'bhw', 'admin', 'system')),
  -- Set for rows created offline by a BHW, so retried syncs never duplicate them.
  local_id    TEXT UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS must be enabled; permissive policy is acceptable for the hackathon demo only.
ALTER TABLE public.connection_test ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for hackathon" ON public.connection_test;
CREATE POLICY "Allow all for hackathon"
  ON public.connection_test
  FOR ALL
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT ON public.connection_test TO anon, authenticated;

INSERT INTO public.connection_test (message, client_type)
SELECT * FROM (VALUES
  ('Initial system test', 'system'),
  ('Hackathon demo ready', 'system')
) AS seed(message, client_type)
WHERE NOT EXISTS (SELECT 1 FROM public.connection_test WHERE client_type = 'system');

-- ===== migrations/20240101000100_care_hierarchy.sql =====
-- TULOY Health: relational chain of command
--   admins  ->  bhws  ->  patients  ->  records
--
-- Admin creates/manages BHWs, BHWs register patients and log field records
-- (often offline, synced later), patients read the records their BHW created.
--
-- local_id columns let offline-created rows be upserted idempotently: if a sync
-- is retried after a partial failure, the same row is never inserted twice.

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name  TEXT NOT NULL,
  email      TEXT NOT NULL UNIQUE,
  office     TEXT NOT NULL DEFAULT 'Rural Health Unit',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- bhws (Barangay Health Workers), managed by an admin
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bhws (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id   UUID NOT NULL REFERENCES public.admins(id) ON DELETE RESTRICT,
  full_name  TEXT NOT NULL,
  email      TEXT UNIQUE,
  phone      TEXT,
  barangay   TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS bhws_admin_id_idx ON public.bhws(admin_id);

-- ---------------------------------------------------------------------------
-- patients, assigned to a BHW
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.patients (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bhw_id     UUID REFERENCES public.bhws(id) ON DELETE SET NULL,
  full_name  TEXT NOT NULL,
  sex        TEXT CHECK (sex IN ('F', 'M')),
  birth_date DATE,
  barangay   TEXT,
  address    TEXT,
  latitude   DOUBLE PRECISION,
  longitude  DOUBLE PRECISION,
  local_id   TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS patients_bhw_id_idx ON public.patients(bhw_id);

-- ---------------------------------------------------------------------------
-- records: visits, health updates and appointments a BHW logs for a patient
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.records (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id    UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  bhw_id        UUID REFERENCES public.bhws(id) ON DELETE SET NULL,
  record_type   TEXT NOT NULL CHECK (record_type IN ('visit', 'health_update', 'appointment')),
  title         TEXT NOT NULL,
  notes         TEXT,
  systolic      INTEGER CHECK (systolic BETWEEN 50 AND 260),
  diastolic     INTEGER CHECK (diastolic BETWEEN 30 AND 180),
  temperature_c NUMERIC(4, 1) CHECK (temperature_c BETWEEN 30 AND 45),
  weight_kg     NUMERIC(5, 1) CHECK (weight_kg BETWEEN 1 AND 400),
  scheduled_at  TIMESTAMPTZ,
  status        TEXT CHECK (status IN ('scheduled', 'completed', 'missed')),
  source        TEXT NOT NULL DEFAULT 'online' CHECK (source IN ('online', 'offline_sync')),
  local_id      TEXT UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS records_patient_id_idx ON public.records(patient_id);
CREATE INDEX IF NOT EXISTS records_bhw_id_idx ON public.records(bhw_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- RLS is ENABLED on every table. Policies are permissive for the hackathon demo
-- (no login flow; roles are hardcoded demo personas). Production must replace
-- these with auth.uid()-based policies, e.g. BHWs only see assigned patients.
-- No DELETE grant: the demo never deletes data from the client.
-- ---------------------------------------------------------------------------
ALTER TABLE public.admins   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bhws     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.records  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hackathon demo access" ON public.admins;
CREATE POLICY "Hackathon demo access" ON public.admins
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.bhws;
CREATE POLICY "Hackathon demo access" ON public.bhws
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.patients;
CREATE POLICY "Hackathon demo access" ON public.patients
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Hackathon demo access" ON public.records;
CREATE POLICY "Hackathon demo access" ON public.records
  FOR ALL USING (true) WITH CHECK (true);

GRANT SELECT                 ON public.admins   TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.bhws     TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.patients TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.records  TO anon, authenticated;

-- ===== seed.sql =====
-- TULOY Health demo seed: Admin -> BHWs -> Patients -> Records
-- All data is synthetic DEMO DATA. Fixed UUIDs match the demo personas in
-- apps/mobile/src/shared/config/demo.ts. Safe to re-run (ON CONFLICT DO NOTHING).

-- Admin (Demo persona for "Demo as Admin")
INSERT INTO public.admins (id, full_name, email, office) VALUES
  ('a0000000-0000-4000-8000-000000000001', 'Demo Admin (RHU Nurse)', 'demo.admin@tuloy.test', 'Demo Rural Health Unit')
ON CONFLICT (id) DO NOTHING;

-- BHWs managed by the admin (bhw ...001 is the "Demo as BHW" persona)
INSERT INTO public.bhws (id, admin_id, full_name, email, phone, barangay, status) VALUES
  ('b0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'Demo BHW Maria', 'demo.bhw1@tuloy.test', '0900-000-0001', 'Brgy. Demo San Isidro', 'active'),
  ('b0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'Demo BHW Jose',  'demo.bhw2@tuloy.test', '0900-000-0002', 'Brgy. Demo Malinis',    'active'),
  ('b0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000001', 'Demo BHW Ana',   'demo.bhw3@tuloy.test', '0900-000-0003', 'Brgy. Demo Bagong Pag-asa', 'inactive')
ON CONFLICT (id) DO NOTHING;

-- Patients assigned to BHWs (patient ...001 is the "Demo as Patient" persona)
INSERT INTO public.patients (id, bhw_id, full_name, sex, birth_date, barangay, address, latitude, longitude) VALUES
  ('c0000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'Demo Patient Juana', 'F', '1968-04-12', 'Brgy. Demo San Isidro', 'Purok 1 (demo)', 14.6042, 120.9822),
  ('c0000000-0000-4000-8000-000000000002', 'b0000000-0000-4000-8000-000000000001', 'Demo Patient Pedro', 'M', '1955-09-30', 'Brgy. Demo San Isidro', 'Purok 2 (demo)', 14.5968, 120.9890),
  ('c0000000-0000-4000-8000-000000000003', 'b0000000-0000-4000-8000-000000000001', 'Demo Patient Rosa',  'F', '1990-01-05', 'Brgy. Demo San Isidro', 'Purok 3 (demo)', 14.5931, 120.9801),
  ('c0000000-0000-4000-8000-000000000004', 'b0000000-0000-4000-8000-000000000002', 'Demo Patient Lito',  'M', '1972-06-18', 'Brgy. Demo Malinis',    'Purok 1 (demo)', 14.6080, 120.9935),
  ('c0000000-0000-4000-8000-000000000005', 'b0000000-0000-4000-8000-000000000002', 'Demo Patient Carmen','F', '1983-11-23', 'Brgy. Demo Malinis',    'Purok 4 (demo)', 14.6011, 120.9958)
ON CONFLICT (id) DO NOTHING;

-- Records created by BHWs for their patients
INSERT INTO public.records (id, patient_id, bhw_id, record_type, title, notes, systolic, diastolic, temperature_c, weight_kg, scheduled_at, status, created_at) VALUES
  ('d0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'visit',         'Home visit: BP check',        'Demo note: patient doing well, advised low-salt diet.', 142, 90, 36.7, 61.5, NULL, NULL, NOW() - INTERVAL '6 days'),
  ('d0000000-0000-4000-8000-000000000002', 'c0000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'health_update', 'Maintenance meds refilled',   'Demo note: 30-day supply given.',                       NULL, NULL, NULL, NULL, NULL, NULL, NOW() - INTERVAL '3 days'),
  ('d0000000-0000-4000-8000-000000000003', 'c0000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'appointment',   'Follow-up BP check at RHU',   'Demo note: bring medication list.',                     NULL, NULL, NULL, NULL, NOW() + INTERVAL '4 days', 'scheduled', NOW() - INTERVAL '3 days'),
  ('d0000000-0000-4000-8000-000000000004', 'c0000000-0000-4000-8000-000000000002', 'b0000000-0000-4000-8000-000000000001', 'visit',         'Home visit: diabetes check',  'Demo note: blood sugar log reviewed.',                  128, 82, 36.5, 70.2, NULL, NULL, NOW() - INTERVAL '2 days'),
  ('d0000000-0000-4000-8000-000000000005', 'c0000000-0000-4000-8000-000000000003', 'b0000000-0000-4000-8000-000000000001', 'appointment',   'Prenatal check-up',           'Demo note: 2nd trimester visit.',                       NULL, NULL, NULL, NULL, NOW() + INTERVAL '9 days', 'scheduled', NOW() - INTERVAL '1 day'),
  ('d0000000-0000-4000-8000-000000000006', 'c0000000-0000-4000-8000-000000000004', 'b0000000-0000-4000-8000-000000000002', 'visit',         'Home visit: TB DOTS',         'Demo note: medication adherence confirmed.',            118, 76, 37.1, 58.0, NULL, NULL, NOW() - INTERVAL '1 day'),
  ('d0000000-0000-4000-8000-000000000007', 'c0000000-0000-4000-8000-000000000005', 'b0000000-0000-4000-8000-000000000002', 'health_update', 'Vaccination record updated', 'Demo note: flu vaccine given.',                         NULL, NULL, NULL, NULL, NULL, NULL, NOW() - INTERVAL '5 hours')
ON CONFLICT (id) DO NOTHING;

-- Make the new tables visible to the Data API immediately.
NOTIFY pgrst, 'reload schema';
