// Generates dist/sw.js after `expo export --platform web` (Spec 02, OC-10.1).
// Usage: node scripts/build-sw.mjs [distDir]   (default: ./dist)
// Plain Node, no dependencies. The precache list is every file in dist/
// except sw.js, source maps and dot-files; the version is a content hash,
// so it changes exactly when any exported file changes.

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(process.argv[2] ?? join(here, '..', 'dist'));
const templatePath = join(here, 'sw-template.js');
// The whole statement, so the mention in the template's header comment is not matched.
const PLACEHOLDER = 'const MANIFEST = self.__PRECACHE__;';

function fail(message) {
  console.error(`build-sw: ${message}`);
  process.exit(1);
}

if (!existsSync(join(dist, 'index.html'))) fail(`${join(dist, 'index.html')} not found. Run "expo export --platform web" first.`);

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.')) continue; // dot-files and dot-folders (e.g. _expo/.routes.json)
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

/** index.html → / ; a/index.html → /a ; a/b.html → /a/b (same rule as routeKey in the template). */
export function routeKey(path) {
  let p = '/' + path.replace(/\.html$/, '');
  p = p.replace(/\/index$/, '');
  return p === '' || p === '/index' ? '/' : p;
}

const files = walk(dist)
  .map((full) => relative(dist, full).split(sep).join('/'))
  .filter((p) => p !== 'sw.js' && !p.endsWith('.map'))
  .sort();

const hash = createHash('sha256');
const routes = [];
const assets = [];
let notFound = null;
for (const path of files) {
  const content = readFileSync(join(dist, path));
  hash.update(`${path}\0${createHash('sha256').update(content).digest('hex')}\n`);
  if (path.endsWith('.html')) {
    const url = routeKey(path);
    routes.push({ url, file: encodeURI('/' + path) });
    if (path === '+not-found.html') notFound = url;
  } else {
    assets.push({ url: encodeURI('/' + path) });
  }
}

if (routes.length === 0) fail('no exported HTML routes found in dist/.');

const version = hash.digest('hex').slice(0, 12);
const template = readFileSync(templatePath, 'utf8');
if (!template.includes(PLACEHOLDER)) fail(`${templatePath} has no ${PLACEHOLDER} placeholder.`);

const manifest = { version, routes, assets, notFound };
if (template.split(PLACEHOLDER).length !== 2) fail(`${templatePath} must contain "${PLACEHOLDER}" exactly once.`);
// Function replacer: "$" sequences in the JSON are inserted literally.
const output = `// GENERATED by scripts/build-sw.mjs from scripts/sw-template.js. Do not edit.\n${template.replace(
  PLACEHOLDER,
  () => `const MANIFEST = ${JSON.stringify(manifest)};`
)}`;
writeFileSync(join(dist, 'sw.js'), output.replace(/\r\n/g, '\n'));
console.log(`sw.js: ${routes.length} routes, ${assets.length} assets, version ${version}`);
